import React, { useMemo, useState } from "react";
import { Package, Plus, Trash2, X } from "lucide-react";
import StatCard from "../components/shared/StatCard";
import { COLORS } from "../data/theme";

const statuses = ["កំពុងប្រើ", "នៅស្តុក", "ជួសជុល", "បាត់/លុបចេញ"];
const initialForm = (employees) => ({ assetCode: "", name: "", category: "កុំព្យូទ័រ", assignedTo: "", status: "នៅស្តុក", purchaseDate: "", value: "", serialNumber: "", note: "" });

export default function AssetManagementPage({ employees = [], assets = [], setAssets }) {
  const [showForm, setShowForm] = useState(false); const [form, setForm] = useState(() => initialForm(employees)); const [error, setError] = useState("");
  const totalValue = useMemo(() => assets.reduce((sum, item) => sum + Number(item.value || 0), 0), [assets]);
  const save = async () => {
    if (!form.assetCode.trim() || !form.name.trim()) { setError("សូមបំពេញលេខកូដ និងឈ្មោះទ្រព្យសម្បត្តិ"); return; }
    if (assets.some((a) => a.assetCode.toLowerCase() === form.assetCode.trim().toLowerCase())) { setError("លេខកូដទ្រព្យសម្បត្តិនេះមានរួចហើយ"); return; }
    const employee = employees.find((item) => item.id === form.assignedTo);
    await setAssets((list) => [{ assetId: `AST-${Date.now()}`, ...form, assetCode: form.assetCode.trim(), name: form.name.trim(), value: Number(form.value || 0), assignedToName: employee?.name || "", createdAt: new Date().toISOString() }, ...list]);
    setForm(initialForm(employees)); setShowForm(false); setError("");
  };
  return <>
    <div className="flex items-start justify-between mb-5 sm:mb-6 gap-3 flex-wrap"><div><h1 className="text-lg sm:text-[22px] font-bold text-[#1E2333]">គ្រប់គ្រងទ្រព្យសម្បត្តិ</h1><p className="text-xs sm:text-sm text-[#8A8FA3] mt-1">កត់ត្រា និងតាមដានទ្រព្យសម្បត្តិរបស់ស្ថាប័ន</p></div><button onClick={()=>setShowForm(true)} className="flex items-center gap-2 bg-[#2A3F8F] text-white text-sm font-semibold rounded-xl px-4 py-2.5"><Plus size={16}/>បន្ថែមទ្រព្យសម្បត្តិ</button></div>
    <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-6"><StatCard icon={Package} label="ទ្រព្យសម្បត្តិសរុប" value={assets.length} sub="កំណត់ត្រាទាំងអស់" iconBg={COLORS.primaryLight} iconColor={COLORS.primary} chartColor={COLORS.primary}/><StatCard icon={Package} label="កំពុងប្រើ" value={assets.filter(a=>a.status==="កំពុងប្រើ").length} sub="បានប្រគល់ឲ្យប្រើប្រាស់" iconBg={COLORS.greenLight} iconColor={COLORS.green} chartColor={COLORS.green}/><StatCard icon={Package} label="តម្លៃសរុប" value={`${totalValue.toLocaleString()} $`} sub="តម្លៃទិញដែលបានកត់ត្រា" iconBg={COLORS.amberLight} iconColor={COLORS.accent} chartColor={COLORS.accent}/></div>
    <div className="bg-white rounded-2xl border border-[#EBEDF3] overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="bg-[#F7F8FB] text-[#8A8FA3] text-xs"><th className="text-right font-medium px-5 py-3">លេខកូដ / ទ្រព្យសម្បត្តិ</th><th className="text-right font-medium px-5 py-3">ប្រភេទ</th><th className="text-right font-medium px-5 py-3">អ្នកទទួលខុសត្រូវ</th><th className="text-right font-medium px-5 py-3">តម្លៃ</th><th className="text-right font-medium px-5 py-3">ស្ថានភាព</th><th className="px-4"/></tr></thead><tbody>{assets.map(a=><tr key={a.assetId} className="border-t border-[#EBEDF3]"><td className="px-5 py-3.5"><div className="font-medium text-[#1E2333]">{a.name}</div><div className="text-xs text-[#8A8FA3]">{a.assetCode}{a.serialNumber?` · ${a.serialNumber}`:""}</div></td><td className="px-5 py-3.5 text-[#5B5F73]">{a.category}</td><td className="px-5 py-3.5 text-[#5B5F73]">{a.assignedToName||"—"}</td><td className="px-5 py-3.5">{Number(a.value||0).toLocaleString()} $</td><td className="px-5 py-3.5"><span className={`rounded-full px-2.5 py-1 text-xs font-medium ${a.status==="កំពុងប្រើ"?"bg-[#E9F7EF] text-[#3FA66B]":a.status==="ជួសជុល"?"bg-[#FDF3E3] text-[#E8A33D]":"bg-[#EEF1FB] text-[#2A3F8F]"}`}>{a.status}</span></td><td className="px-4 py-3.5"><button onClick={()=>setAssets(list=>list.filter(item=>item.assetId!==a.assetId))} className="p-2 rounded-lg text-[#D9614F] hover:bg-[#FBEBE8]" aria-label="លុប"><Trash2 size={16}/></button></td></tr>)}{!assets.length&&<tr><td colSpan="6" className="text-center py-12 text-[#8A8FA3]">មិនទាន់មានទ្រព្យសម្បត្តិទេ។</td></tr>}</tbody></table></div></div>
    {showForm&&<div className="fixed inset-0 z-50 bg-black/40 flex items-center justify-center p-4"><div className="bg-white rounded-2xl w-full max-w-xl p-5"><div className="flex justify-between mb-4"><h2 className="font-bold text-[#1E2333]">បន្ថែមទ្រព្យសម្បត្តិ</h2><button onClick={()=>setShowForm(false)}><X size={20}/></button></div><div className="grid grid-cols-1 sm:grid-cols-2 gap-3"><Input label="លេខកូដ *" value={form.assetCode} change={v=>setForm({...form,assetCode:v})} placeholder="AST-001"/><Input label="ឈ្មោះ *" value={form.name} change={v=>setForm({...form,name:v})}/><Input label="ប្រភេទ" value={form.category} change={v=>setForm({...form,category:v})}/><label className="text-xs text-[#5B5F73]">ស្ថានភាព<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})} className="mt-1 w-full bg-[#F5F6FA] rounded-xl px-3 py-2.5 text-sm">{statuses.map(s=><option key={s}>{s}</option>)}</select></label><label className="text-xs text-[#5B5F73]">ប្រគល់ឲ្យ<select value={form.assignedTo} onChange={e=>setForm({...form,assignedTo:e.target.value})} className="mt-1 w-full bg-[#F5F6FA] rounded-xl px-3 py-2.5 text-sm"><option value="">មិនទាន់ប្រគល់</option>{employees.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label><Input label="តម្លៃ (USD)" type="number" value={form.value} change={v=>setForm({...form,value:v})}/><Input label="ថ្ងៃទិញ" type="date" value={form.purchaseDate} change={v=>setForm({...form,purchaseDate:v})}/><Input label="Serial Number" value={form.serialNumber} change={v=>setForm({...form,serialNumber:v})}/><div className="sm:col-span-2"><Input label="កំណត់ចំណាំ" value={form.note} change={v=>setForm({...form,note:v})}/></div></div>{error&&<p className="text-sm text-[#D9614F] mt-3">{error}</p>}<div className="flex gap-2 mt-5"><button onClick={()=>setShowForm(false)} className="flex-1 border border-[#EBEDF3] rounded-xl py-2.5 text-sm">បោះបង់</button><button onClick={save} className="flex-1 bg-[#2A3F8F] text-white rounded-xl py-2.5 text-sm font-semibold">រក្សាទុក</button></div></div></div>}
  </>;
}
function Input({label,value,change,type="text",placeholder}) { return <label className="text-xs text-[#5B5F73]">{label}<input type={type} value={value} onChange={e=>change(e.target.value)} placeholder={placeholder} className="mt-1 w-full bg-[#F5F6FA] rounded-xl px-3 py-2.5 text-sm outline-none"/></label>; }
