import React, { useMemo, useState } from "react";
import { Banknote, Plus, Trash2, X } from "lucide-react";
import StatCard from "../components/shared/StatCard";
import { COLORS } from "../data/theme";

const initialForm = (employees) => ({ employeeId: employees[0]?.id || "", amount: "", paidAmount: "0", monthlyPayment: "", startDate: new Date().toISOString().slice(0, 10), purpose: "", status: "សកម្ម" });

export default function StaffLoanPage({ employees = [], loans = [], setLoans }) {
  const [showForm,setShowForm]=useState(false); const [form,setForm]=useState(()=>initialForm(employees)); const [error,setError]=useState("");
  const summary=useMemo(()=>({outstanding:loans.reduce((s,l)=>s+Math.max(0,Number(l.amount||0)-Number(l.paidAmount||0)),0), active:loans.filter(l=>l.status==="សកម្ម").length, repaid:loans.filter(l=>Number(l.paidAmount)>=Number(l.amount)&&Number(l.amount)>0).length}),[loans]);
  const save=async()=>{ if(!form.employeeId||Number(form.amount)<=0||Number(form.monthlyPayment)<0){setError("សូមជ្រើសបុគ្គលិក និងបំពេញចំនួនកម្ចីឲ្យត្រឹមត្រូវ");return;} if(Number(form.paidAmount)>Number(form.amount)){setError("ចំនួនបានសងមិនអាចលើសចំនួនកម្ចី");return;} const e=employees.find(x=>x.id===form.employeeId);await setLoans(list=>[{loanId:`LOAN-${Date.now()}`,...form,amount:Number(form.amount),paidAmount:Number(form.paidAmount),monthlyPayment:Number(form.monthlyPayment),employeeName:e.name,branch:e.branch,createdAt:new Date().toISOString()},...list]);setForm(initialForm(employees));setError("");setShowForm(false);};
  return <>
    <div className="flex items-start justify-between mb-5 sm:mb-6 gap-3 flex-wrap"><div><h1 className="text-lg sm:text-[22px] font-bold text-[#1E2333]">កម្ចីបុគ្គលិក</h1><p className="text-xs sm:text-sm text-[#8A8FA3] mt-1">កត់ត្រា និងតាមដានការសងកម្ចីរបស់បុគ្គលិក</p></div><button onClick={()=>setShowForm(true)} className="flex items-center gap-2 bg-[#2A3F8F] text-white text-sm font-semibold rounded-xl px-4 py-2.5"><Plus size={16}/>បន្ថែមកម្ចី</button></div>
    <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-6"><StatCard icon={Banknote} label="កម្ចីកំពុងសកម្ម" value={summary.active} sub="គណនីកម្ចី" iconBg={COLORS.primaryLight} iconColor={COLORS.primary} chartColor={COLORS.primary}/><StatCard icon={Banknote} label="សមតុល្យនៅសល់" value={`${summary.outstanding.toLocaleString()} $`} sub="ប្រាក់នៅមិនទាន់សង" iconBg={COLORS.amberLight} iconColor={COLORS.accent} chartColor={COLORS.accent}/><StatCard icon={Banknote} label="បានសងរួច" value={summary.repaid} sub="បិទកម្ចីរួចរាល់" iconBg={COLORS.greenLight} iconColor={COLORS.green} chartColor={COLORS.green}/></div>
    <div className="bg-white rounded-2xl border border-[#EBEDF3] overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="bg-[#F7F8FB] text-[#8A8FA3] text-xs"><th className="text-right font-medium px-5 py-3">បុគ្គលិក</th><th className="text-right font-medium px-5 py-3">ថ្ងៃចាប់ផ្តើម</th><th className="text-right font-medium px-5 py-3">ចំនួនកម្ចី</th><th className="text-right font-medium px-5 py-3">បានសង</th><th className="text-right font-medium px-5 py-3">នៅសល់</th><th className="text-right font-medium px-5 py-3">ស្ថានភាព</th><th className="px-4"/></tr></thead><tbody>{loans.map(l=>{const balance=Math.max(0,Number(l.amount)-Number(l.paidAmount));return <tr key={l.loanId} className="border-t border-[#EBEDF3]"><td className="px-5 py-3.5"><div className="font-medium text-[#1E2333]">{l.employeeName}</div><div className="text-xs text-[#8A8FA3]">{l.branch}</div></td><td className="px-5 py-3.5 text-[#5B5F73]">{l.startDate}</td><td className="px-5 py-3.5">{Number(l.amount).toLocaleString()} $</td><td className="px-5 py-3.5">{Number(l.paidAmount).toLocaleString()} $</td><td className="px-5 py-3.5 font-medium">{balance.toLocaleString()} $</td><td className="px-5 py-3.5"><span className={`rounded-full px-2.5 py-1 text-xs font-medium ${balance===0?"bg-[#E9F7EF] text-[#3FA66B]":"bg-[#EEF1FB] text-[#2A3F8F]"}`}>{balance===0?"បានសងរួច":l.status}</span></td><td className="px-4 py-3.5"><button onClick={()=>setLoans(list=>list.filter(x=>x.loanId!==l.loanId))} className="p-2 rounded-lg text-[#D9614F] hover:bg-[#FBEBE8]" aria-label="លុប"><Trash2 size={16}/></button></td></tr>})}{!loans.length&&<tr><td colSpan="7" className="text-center py-12 text-[#8A8FA3]">មិនទាន់មានកម្ចីបុគ្គលិកទេ។</td></tr>}</tbody></table></div></div>
    {showForm&&<div className="fixed inset-0 z-50 bg-black/40 flex items-center justify-center p-4"><div className="bg-white rounded-2xl w-full max-w-lg p-5"><div className="flex justify-between mb-4"><h2 className="font-bold text-[#1E2333]">បន្ថែមកម្ចីបុគ្គលិក</h2><button onClick={()=>setShowForm(false)}><X size={20}/></button></div><div className="grid grid-cols-1 sm:grid-cols-2 gap-3"><label className="text-xs text-[#5B5F73] sm:col-span-2">បុគ្គលិក<select value={form.employeeId} onChange={e=>setForm({...form,employeeId:e.target.value})} className="mt-1 w-full bg-[#F5F6FA] rounded-xl px-3 py-2.5 text-sm">{employees.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label><Input label="ចំនួនកម្ចី (USD) *" type="number" value={form.amount} change={v=>setForm({...form,amount:v})}/><Input label="បានសងរួច (USD)" type="number" value={form.paidAmount} change={v=>setForm({...form,paidAmount:v})}/><Input label="សងប្រចាំខែ (USD)" type="number" value={form.monthlyPayment} change={v=>setForm({...form,monthlyPayment:v})}/><Input label="ថ្ងៃចាប់ផ្តើម" type="date" value={form.startDate} change={v=>setForm({...form,startDate:v})}/><div className="sm:col-span-2"><Input label="គោលបំណង" value={form.purpose} change={v=>setForm({...form,purpose:v})}/></div></div>{error&&<p className="text-sm text-[#D9614F] mt-3">{error}</p>}<div className="flex gap-2 mt-5"><button onClick={()=>setShowForm(false)} className="flex-1 border border-[#EBEDF3] rounded-xl py-2.5 text-sm">បោះបង់</button><button onClick={save} className="flex-1 bg-[#2A3F8F] text-white rounded-xl py-2.5 text-sm font-semibold">រក្សាទុក</button></div></div></div>}
  </>;
}
function Input({label,value,change,type="text"}){return <label className="text-xs text-[#5B5F73]">{label}<input type={type} min={type==="number"?"0":undefined} value={value} onChange={e=>change(e.target.value)} className="mt-1 w-full bg-[#F5F6FA] rounded-xl px-3 py-2.5 text-sm outline-none"/></label>}
