import React, { useEffect, useState } from "react";
import { Bell, CheckCircle2, Send } from "lucide-react";
import { loadSettingsDoc, saveSettingsDoc } from "../firebase/settingsDoc";

const defaults = { enabled: false, chatId: "", onCheckIn: true, onLeaveRequest: true, onLeaveDecision: true, onLate: false };

export default function TelegramBotPage({ outbox = [], setOutbox }) {
  const [settings, setSettings] = useState(defaults); const [loading, setLoading] = useState(true); const [saved, setSaved] = useState(false); const [message, setMessage] = useState("");
  useEffect(() => { loadSettingsDoc("telegram", defaults).then((data)=>{setSettings({...defaults,...data});setLoading(false);}); }, []);
  const save = async () => { await saveSettingsDoc("telegram", settings); setSaved(true); setTimeout(()=>setSaved(false),2500); };
  const queueTest = async () => { if(!settings.chatId.trim()){setMessage("សូមបំពេញ Telegram Chat ID ជាមុន");return;} await setOutbox((list)=>[{id:`TG-${Date.now()}`, chatId:settings.chatId.trim(), type:"test", message:"✅ Borribo HRMS: Telegram integration test", status:"រង់ចាំផ្ញើ", createdAt:new Date().toISOString()},...list]); setMessage("បានបង្កើត Test Message ក្នុង queue រួចរាល់"); };
  if(loading)return <div className="py-24 text-center text-sm text-[#8A8FA3]">កំពុងផ្ទុក...</div>;
  return <>
    <div className="mb-5 sm:mb-6"><h1 className="text-lg sm:text-[22px] font-bold text-[#1E2333]">Telegram Bot</h1><p className="text-xs sm:text-sm text-[#8A8FA3] mt-1">រៀបចំសារជូនដំណឹងពី HRMS ទៅក្រុម Telegram</p></div>
    <div className="grid grid-cols-1 lg:grid-cols-3 gap-4"><div className="lg:col-span-2 bg-white rounded-2xl border border-[#EBEDF3] p-5"><div className="flex items-center justify-between pb-4 border-b border-[#EBEDF3]"><div><h2 className="font-semibold text-[#1E2333]">ការកំណត់ជូនដំណឹង</h2><p className="text-xs text-[#8A8FA3] mt-1">Bot Token មិនត្រូវដាក់ក្នុង website ទេ ដើម្បីរក្សាសុវត្ថិភាព។</p></div><button onClick={()=>setSettings({...settings,enabled:!settings.enabled})} className={`w-11 h-6 rounded-full transition-colors ${settings.enabled?"bg-[#3FA66B]":"bg-[#D9DCE6]"}`}><span className={`block w-5 h-5 rounded-full bg-white mx-0.5 transition-transform ${settings.enabled?"translate-x-5":""}`}/></button></div><label className="block text-xs text-[#5B5F73] mt-4">Telegram Chat ID<input value={settings.chatId} onChange={e=>setSettings({...settings,chatId:e.target.value})} placeholder="ឧ. -1001234567890" className="mt-1 w-full bg-[#F5F6FA] rounded-xl px-3 py-2.5 text-sm outline-none"/></label><div className="mt-4 flex flex-col divide-y divide-[#EBEDF3]">{[["onCheckIn","Check-in / Check-out"],["onLeaveRequest","សំណើសុំច្បាប់ថ្មី"],["onLeaveDecision","ការអនុម័ត / បដិសេធច្បាប់"],["onLate","ជូនដំណឹងមកយឺត"]].map(([key,label])=><label key={key} className="py-3 flex items-center justify-between text-sm text-[#1E2333]"><span>{label}</span><input type="checkbox" checked={Boolean(settings[key])} onChange={e=>setSettings({...settings,[key]:e.target.checked})} className="w-4 h-4 accent-[#2A3F8F]"/></label>)}</div><div className="flex flex-wrap gap-2 mt-5"><button onClick={save} className="bg-[#2A3F8F] text-white rounded-xl px-4 py-2.5 text-sm font-semibold">{saved?"បានរក្សាទុករួច":"រក្សាទុកការកំណត់"}</button><button onClick={queueTest} className="border border-[#EBEDF3] text-[#2A3F8F] rounded-xl px-4 py-2.5 text-sm font-semibold flex gap-2 items-center"><Send size={15}/>បង្កើត Test Message</button></div>{message&&<p className={`mt-3 text-sm ${message.startsWith("បាន")?"text-[#3FA66B]":"text-[#D9614F]"}`}>{message}</p>}</div><div className="bg-white rounded-2xl border border-[#EBEDF3] p-5"><Bell className="text-[#2A3F8F] mb-3" size={22}/><h2 className="font-semibold text-[#1E2333]">ជំហានភ្ជាប់ពិត</h2><ol className="mt-3 text-sm text-[#5B5F73] leading-6 list-decimal pl-5"><li>បង្កើត Bot ជាមួយ @BotFather</li><li>បន្ថែម Bot ចូល Telegram Group</li><li>ដាក់ Chat ID ខាងឆ្វេង</li><li>IT ដាក់ Bot Token ជា server secret</li><li>Server អាន queue ហើយផ្ញើសារ</li></ol><p className="mt-4 text-xs leading-5 text-[#8A8FA3]">Website នេះរក្សាទុកតែ queue សារ និង setting។ Token ត្រូវនៅ server ដាច់ដោយឡែក មិនត្រូវ push ទៅ GitHub ឬដាក់ក្នុង .env frontend ទេ។</p></div></div>
    <div className="bg-white rounded-2xl border border-[#EBEDF3] overflow-hidden mt-5"><div className="px-5 py-4 flex gap-2 items-center font-semibold text-[#1E2333]"><CheckCircle2 size={17} className="text-[#3FA66B]"/> Telegram Message Queue</div><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="bg-[#F7F8FB] text-xs text-[#8A8FA3]"><th className="text-right px-5 py-3">សារ</th><th className="text-right px-5 py-3">Chat ID</th><th className="text-right px-5 py-3">ស្ថានភាព</th><th className="text-right px-5 py-3">ពេលវេលា</th></tr></thead><tbody>{outbox.slice(0,10).map(item=><tr key={item.id} className="border-t border-[#EBEDF3]"><td className="px-5 py-3">{item.message}</td><td className="px-5 py-3">{item.chatId}</td><td className="px-5 py-3"><span className="bg-[#FDF3E3] text-[#E8A33D] rounded-full px-2.5 py-1 text-xs">{item.status}</span></td><td className="px-5 py-3 text-[#8A8FA3]">{item.createdAt?.slice(0,16).replace("T"," ")}</td></tr>)}{!outbox.length&&<tr><td colSpan="4" className="text-center py-10 text-[#8A8FA3]">មិនទាន់មានសារក្នុង queue ទេ</td></tr>}</tbody></table></div></div>
  </>;
}
